# Generated by Django 2.0.4 on 2018-04-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
