# Generated by Django 2.0.4 on 2018-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20180414_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='email_id',
            field=models.EmailField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
