# Generated by Django 2.0.4 on 2018-04-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20180414_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='department_id',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
